# Generated by Django 3.2.12 on 2022-02-23 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Тип изделия',
                'verbose_name_plural': 'Тип изделий',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('series', models.CharField(max_length=40, null=True, verbose_name='Серия')),
                ('article', models.CharField(max_length=40, null=True, verbose_name='Артикул')),
                ('width', models.PositiveIntegerField(null=True, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(null=True, verbose_name='Высота')),
                ('price', models.PositiveIntegerField(null=True, verbose_name='Цена')),
                ('date_added', models.DateTimeField(null=True, verbose_name='Дата добавления')),
                ('photo_file_name', models.CharField(max_length=100, null=True, verbose_name='Фото')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('depth', models.IntegerField(null=True, verbose_name='Глубина')),
                ('countertop_material', models.CharField(max_length=50, null=True, verbose_name='Материал столешницы')),
                ('execution_material', models.CharField(max_length=50, null=True, verbose_name='Материал исполнения')),
                ('purpose', models.CharField(max_length=50, null=True, verbose_name='Назначение')),
                ('disposition', models.CharField(max_length=50, null=True, verbose_name='Расположение')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CatalogueApp.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('CatalogueApp.product',),
        ),
    ]
