# Generated by Django 3.2.12 on 2022-02-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('height', models.IntegerField(verbose_name='Высота')),
                ('depth', models.IntegerField(verbose_name='Глубина')),
                ('countertop_material', models.CharField(max_length=50, verbose_name='Материал столешницы')),
                ('disposition', models.CharField(max_length=50, verbose_name='Расположение')),
                ('execution_material', models.CharField(max_length=50, verbose_name='Материал исполнения')),
                ('purpose', models.CharField(max_length=50, verbose_name='Назначение')),
                ('date_added', models.DateTimeField()),
                ('photo_file_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
                'ordering': ['id'],
            },
        ),
    ]
