# Generated by Django 3.2.12 on 2022-02-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, null=True, verbose_name='Опубликовано'),
        ),
    ]
