# Generated by Django 3.2.12 on 2022-02-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='countertop_material',
            field=models.CharField(max_length=50, null=True, verbose_name='Материал столешницы'),
        ),
        migrations.AlterField(
            model_name='table',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='depth',
            field=models.IntegerField(null=True, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='table',
            name='disposition',
            field=models.CharField(max_length=50, null=True, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='table',
            name='execution_material',
            field=models.CharField(max_length=50, null=True, verbose_name='Материал исполнения'),
        ),
        migrations.AlterField(
            model_name='table',
            name='height',
            field=models.IntegerField(null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='table',
            name='photo_file_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='purpose',
            field=models.CharField(max_length=50, null=True, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='table',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='table',
            name='width',
            field=models.IntegerField(null=True, verbose_name='Ширина'),
        ),
    ]
