# Generated by Django 3.2.12 on 2022-03-05 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0002_alter_product_type_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type_title',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='products', to='CatalogueApp.type', verbose_name='Тип'),
        ),
    ]
