# Generated by Django 3.2.12 on 2022-03-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0003_auto_20220305_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя заказчика')),
                ('email', models.CharField(max_length=50, verbose_name='Почтовый адрес')),
                ('first_activity_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Информация заказчика',
                'verbose_name_plural': 'Информация заказчика',
                'ordering': ['id'],
            },
        ),
    ]
