# Generated by Django 3.2.12 on 2022-03-14 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0004_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id'], 'verbose_name': 'Информация о заказчике', 'verbose_name_plural': 'Информация о заказчике'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_data', models.CharField(max_length=50, verbose_name='Детали заказа')),
                ('date_order', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('price', models.CharField(max_length=50, verbose_name='Стоимость заказа')),
                ('customer', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='CatalogueApp.client', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Информация о заказе',
                'verbose_name_plural': 'Информация о заказе',
                'ordering': ['id'],
            },
        ),
    ]
