# Generated by Django 3.2.12 on 2022-02-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0005_alter_type_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='title',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
