# Generated by Django 3.2.12 on 2022-03-14 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0005_auto_20220314_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_data',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CatalogueApp.client', verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.CharField(max_length=500, null=True, verbose_name='Детали заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(max_length=50, verbose_name='Стоимость заказа'),
        ),
    ]
