# Generated by Django 3.2.12 on 2022-03-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0006_auto_20220315_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='order',
            name='commentary',
            field=models.CharField(max_length=500, null=True, verbose_name='Комментарий к заказу'),
        ),
    ]
