# Generated by Django 3.2.12 on 2022-03-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0006_auto_20220315_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
            ],
            options={
                'verbose_name': 'Дополнительное оснащение',
                'verbose_name_plural': 'Дополнительное оснащение',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('CatalogueApp.product',),
        ),
    ]
