# Generated by Django 3.2.12 on 2022-02-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0008_auto_20220226_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
            ],
            options={
                'verbose_name': 'Шкаф',
                'verbose_name_plural': 'Шкафы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('CatalogueApp.product',),
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
            ],
            options={
                'verbose_name': 'Стеллаж',
                'verbose_name_plural': 'Стеллажи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('CatalogueApp.product',),
        ),
        migrations.RemoveField(
            model_name='type',
            name='subtype',
        ),
        migrations.DeleteModel(
            name='Subtype',
        ),
    ]
