# Generated by Django 3.2.12 on 2022-03-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0008_auto_20220325_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
            ],
            options={
                'verbose_name': 'Стойка',
                'verbose_name_plural': 'Стойки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('CatalogueApp.product',),
        ),
        migrations.RemoveField(
            model_name='product',
            name='doors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mortise',
        ),
        migrations.AddField(
            model_name='product',
            name='disposition',
            field=models.CharField(max_length=50, null=True, verbose_name='Расположение'),
        ),
        migrations.AddField(
            model_name='product',
            name='gas',
            field=models.BooleanField(null=True, verbose_name='Газ'),
        ),
        migrations.AddField(
            model_name='product',
            name='sink_count',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Количество моек'),
        ),
        migrations.AddField(
            model_name='product',
            name='sink_type',
            field=models.CharField(max_length=50, null=True, verbose_name='Тип мойки'),
        ),
        migrations.AddField(
            model_name='product',
            name='titiration_panel',
            field=models.BooleanField(null=True, verbose_name='Табло титирования'),
        ),
        migrations.AddField(
            model_name='product',
            name='water',
            field=models.BooleanField(null=True, verbose_name='Вода'),
        ),
        migrations.AlterField(
            model_name='product',
            name='technology_rack',
            field=models.CharField(choices=[(None, 'Отсутствует'), ('built_in', 'В комплекте'), ('separately', 'Отдельным заказом')], default=None, max_length=30, null=True, verbose_name='Технологическая стойка'),
        ),
    ]
