# Generated by Django 3.2.12 on 2022-03-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0009_auto_20220325_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name': 'Доп. оснащение', 'verbose_name_plural': 'Доп. оснащение'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=50, verbose_name='E-Mail клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_activity_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда зарегистрировался'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CatalogueApp.client', verbose_name='Клиент'),
        ),
    ]
