# Generated by Django 3.2.12 on 2022-02-26 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0009_auto_20220226_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Подтип изделия',
                'verbose_name_plural': 'Подтип изделий',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='type',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CatalogueApp.subtype', verbose_name='Подтип'),
        ),
    ]
