# Generated by Django 3.2.12 on 2022-02-27 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0011_alter_product_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CatalogueApp.type', verbose_name='Тип'),
        ),
    ]
