# Generated by Django 3.2.12 on 2022-03-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0012_product_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='titiration_panel',
        ),
        migrations.AddField(
            model_name='product',
            name='titration_panel',
            field=models.BooleanField(null=True, verbose_name='Табло титрования'),
        ),
        migrations.AlterField(
            model_name='product',
            name='door_quantity',
            field=models.PositiveSmallIntegerField(max_length=50, null=True, verbose_name='Количество дверей'),
        ),
    ]
