# Generated by Django 3.2.12 on 2022-03-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0013_auto_20220325_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='complete_with_drawers',
            field=models.CharField(max_length=50, null=True, verbose_name='Комплектуется с типами тумб'),
        ),
    ]
