# Generated by Django 3.2.12 on 2022-02-27 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0014_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(db_column='type_title', default='Любой', on_delete=django.db.models.deletion.SET_DEFAULT, to='CatalogueApp.type', to_field='title', verbose_name='Тип'),
        ),
    ]
