# Generated by Django 3.2.12 on 2022-03-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0014_product_complete_with_drawers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='door_quantity',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Количество дверей'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf_count',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Количество полок'),
        ),
    ]
