# Generated by Django 3.2.12 on 2022-03-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0007_auto_20220326_0056'),
        ('CatalogueApp', '0016_product_mods'),
    ]

    operations = [
    ]
