# Generated by Django 3.2.12 on 2022-03-28 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0017_merge_0007_auto_20220326_0056_0016_product_mods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtype',
            options={'ordering': ['id'], 'verbose_name': 'Подтип', 'verbose_name_plural': 'Подтип'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default=0, max_length=50, verbose_name='E-Mail клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=0, max_length=100, verbose_name='Имя клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=0, max_length=50, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='radio',
            field=models.CharField(max_length=50, null=True, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='commentary',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='CatalogueApp.type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='subtype',
            name='title',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='Подтип'),
        ),
    ]
