# Generated by Django 3.2.12 on 2022-03-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0018_auto_20220326_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=150, verbose_name='Сумма заказа'),
            preserve_default=False,
        ),
    ]
