# Generated by Django 3.2.12 on 2022-03-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0020_auto_20220328_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comment',
            new_name='commentary',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вариант доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.CharField(default=[], max_length=300, verbose_name='Товары'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=100, verbose_name='E-mail клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Номер телефона клиента'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mods',
            field=models.CharField(max_length=1000, null=True, verbose_name='Модификации'),
        ),
    ]
