# Generated by Django 3.2.12 on 2022-03-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0022_alter_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_correct_photo',
            field=models.BooleanField(default=False, verbose_name='Корректно ли фото'),
        ),
    ]
