# Generated by Django 3.2.12 on 2022-04-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0024_alter_product_photo_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_correct_photo',
        ),
        migrations.AlterField(
            model_name='product',
            name='boxes',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество ящиков'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.CharField(max_length=50, null=True, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='product',
            name='technology_rack',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='Технологическая стойка'),
        ),
    ]
