# Generated by Django 3.2.12 on 2022-04-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0026_alter_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Описание'),
        ),
    ]
