# Generated by Django 3.2.12 on 2022-04-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalogueApp', '0028_auto_20220411_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Цена'),
        ),
    ]
